### ISSUE TITLE
 Plug-in cannot be opened, can be identified.

### ISSUE THREAD

**Issue by qfb594** [pKrime/brignet#22]
Traceback (most recent call last):
  File "C:\Program Files\blender-2.91.2-windows64\2.91\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\brignet-main\__init__.py", line 32, in <module>
    from . import brignet, preferences, loadskeleton
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\brignet-main\brignet.py", line 10, in <module>
    from . import rignetconnect
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\brignet-main\rignetconnect.py", line 7, in <module>
    from torch_geometric.data import Data
  File "C:\Program Files\blender-2.91.2-windows64\2.91\python\lib\site-packages\torch_geometric\__init__.py", line 4, in <module>
    import torch_geometric.data
  File "C:\Program Files\blender-2.91.2-windows64\2.91\python\lib\site-packages\torch_geometric\data\__init__.py", line 1, in <module>
    from .data import Data
  File "C:\Program Files\blender-2.91.2-windows64\2.91\python\lib\site-packages\torch_geometric\data\data.py", line 20, in <module>
    from torch_sparse import SparseTensor
  File "C:\Program Files\blender-2.91.2-windows64\2.91\python\lib\site-packages\torch_sparse\__init__.py", line 19, in <module>
    torch.ops.load_library(spec.origin)
  File "C:\Program Files\blender-2.91.2-windows64\2.91\python\lib\site-packages\torch\_ops.py", line 220, in load_library
    ctypes.CDLL(path)
  File "C:\Program Files\blender-2.91.2-windows64\2.91\python\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 127] The specified program could not be found.

**Comment by qfb594** [comment]
![QQ浏览器截图20221002124721](https://user-images.githubusercontent.com/48076384/193438335-6594fc59-f976-4155-9b6d-b34383090be2.png)

**Comment by ibtehajali67** [comment]
I am also facing same problem ,

**Comment by pKrime** [comment]
Hi, all of that boils down to binary incompatibility between blender and the pytorch libraries. Though there is not much progress in this project at the moment, I am evaluating solutions, please be patient!
