### ISSUE TITLE
When I click Predict RIG, I get an error. What's going on?

### ISSUE THREAD

**Issue by qfb594** [pKrime/brignet#23]
Python: Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\brignet-main\brignet.py", line 220, in invoke
    from . import rignetconnect
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\brignet-main\rignetconnect.py", line 10, in <module>
    from .RigNet.utils.rig_parser import Info
ModuleNotFoundError: No module named 'brignet-main.RigNet.utils'

location: <unknown location>:-1

**Comment by pKrime** [comment]
Hi,

it would seem that Rignet is missing or not found. Does the folder

`C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\brignet-main\RigNet`

exist?

**Comment by qfb594** [comment]
![image](https://user-images.githubusercontent.com/48076384/193637012-fb52958e-e840-4eca-b0c3-a1efaeb3bc8f.png)
All the required documents are here

**Comment by pKrime** [comment]
Hi, sorry for the delay, does the RigNet folder contain a utils subfolder? Does RigNet utils contain .py files? According to the error message, the add-on doesn't seem to find them

**Comment by qfb594** [comment]
The Settings are normal, the required files are there, but the operation is not up.

![QQ浏览器截图20221006105211](https://user-images.githubusercontent.com/48076384/194203648-c6e8845b-a727-47ca-8262-1507bd3edf40.png)
![QQ浏览器截图20221006105154](https://user-images.githubusercontent.com/48076384/194203651-50ec1ebb-8105-4cec-adde-0a559c35a85c.png)
![QQ浏览器截图20221006105227](https://user-images.githubusercontent.com/48076384/194203654-3fc8e708-e2f2-43d3-802e-f0ec8692ecb3.png)

**Comment by Abrahm1234** [comment]
I personal had to manually download everything in the RigNet folder to fix this issue. For some reason it does not download it using git clone? Also Now the rig_parser.py file is present in the RigNet/utils directory. One possible reason for the error could be that the Python environment used by Blender does not have the brignet add-on directory added to its sys.path. You can try adding the following line at the beginning of the brignet.py file to see if it resolves the issue:

import sys
sys.path.append('/User/Administrator/Path/To/Dir')
Copy
This will add the brignet add-on directory to the Python path, allowing Blender to find and import the RigNet module.
