### ISSUE TITLE
error while trying to enable the addon

### ISSUE THREAD

**Issue by qtabdullah** [pKrime/brignet#26]
hello i have tried enabling the addon but it gives this error:
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\modules\addon_utils.py", line 369, in enable
    mod.register()
  File "C:\Users\Name\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\brignet\__init__.py", line 70, in register
    BrignetPrefs.check_cuda()
  File "C:\Users\Name\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\brignet\preferences.py", line 41, in check_cuda
    BrignetPrefs._cuda_info = cuda_utils.CudaDetect()
  File "C:\Users\Name\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\brignet\setup_utils\cuda_utils.py", line 24, in __init__
    self.has_cuda_device()
  File "C:\Users\Name\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\brignet\setup_utils\cuda_utils.py", line 52, in has_cuda_device
    for device in cprefs.get_devices(bpy.context):
TypeError: 'NoneType' object is not iterable

**Comment by 99bits** [comment]
I have the same problem, using cuda 12.2, blender 3.4
