### ISSUE TITLE
Modules not being found with Pytorch 1.8.1 and Blender 4.0+

### ISSUE THREAD

**Issue by Draise14** [pKrime/brignet#30]
Been trying to install the modules needed to use this addon for Blender 4.0+ and Nvidia RTX 4090, but it seems Blender now uses Python 3.10+, and CUDA 11.8 is recommended. The method to manually build the environment no-longer works, neither can you install the environment through the addon method.. 

```
Python: Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1232, in _handle_fromlist
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\USER\AppData\Roaming\Bforartists\Bforartists\4.1\scripts\addons\brignet-main\rignetconnect.py", line 6, in <module>
    import torch
  File "C:\Users\USER\pinokio\bin\miniconda\envs\brignet37\Lib\site-packages\torch\__init__.py", line 134, in <module>
    raise err
OSError: [WinError 126] The specified module could not be found. Error loading "C:\Users\USER\pinokio\bin\miniconda\envs\brignet37\Lib\site-packages\torch\lib\caffe2_detectron_ops.dll" or one of its dependencies.
```

Ideally we could use the latest pytorch with cuda 11.8

`conda install pytorch==2.2.1 cudatoolkit=11.8 -c pytorch`

`pip install torch-scatter -f https://pytorch-geometric.com/whl/torch-2.2.1+cu118.html`

`pip install torch-sparse -f https://pytorch-geometric.com/whl/torch-2.2.1+cu118.html`

`pip install torch-cluster -f https://pytorch-geometric.com/whl/torch-2.2.1+cu118.html`

`pip install torch-spline-conv -f https://pytorch-geometric.com/whl/torch-2.2.1+cu118.html`

`pip install torch-geometric`

But the addon seems to not be working with the latest....

**Comment by Draise14** [comment]
Update, I have the the CUDA toolkist 12.1 used to compile Blender (no-longer supports 10 or 11.# versions) - that might be the issue....
